In [9]:
import numpy as np

In [10]:
# Задача 1
from collections import Counter

def sort_by_frequency(arr):
    count = Counter(arr) # Считаем частоту встречания элементов
    # Сортируем по частоте, затем по значению
    sorted_arr = sorted(arr, key=lambda x: (count[x], x))

    return np.array(sorted_arr)


arr = np.random.randint(-10, 10, size=(int(1e2)))
print("Изначальный массив:", arr)
sorted_arr = sort_by_frequency(arr)
print("Отсортированный массив по частоте:", sorted_arr)


Изначальный массив: [ -6  -1   4  -1   2   1   0   8  -2   1  -3   0  -2   2 -10   2  -5  -1
 -10   1   4  -9   2  -4  -3  -6  -3   4   5  -1  -5  -3  -5   1   1   0
   9   6   0  -8   2   1  -6   9   6  -5   5  -1   5  -9   4  -5  -7  -2
  -2   5  -7   2   3  -3   7   9  -7  -7   7  -9  -3   6   2  -1   7  -1
  -2   5   9  -5  -5  -7   6  -1   8   4  -5  -2   8  -8   3   2  -2   3
  -1  -3   2  -9   2   9  -8   9   5  -5]
Отсортированный массив по частоте: [ -4 -10 -10  -8  -8  -8  -6  -6  -6   3   3   3   7   7   7   8   8   8
  -9  -9  -9  -9   0   0   0   0   6   6   6   6  -7  -7  -7  -7  -7   4
   4   4   4   4   1   1   1   1   1   1   5   5   5   5   5   5   9   9
   9   9   9   9  -3  -3  -3  -3  -3  -3  -3  -2  -2  -2  -2  -2  -2  -2
  -5  -5  -5  -5  -5  -5  -5  -5  -5  -1  -1  -1  -1  -1  -1  -1  -1  -1
   2   2   2   2   2   2   2   2   2   2]


In [14]:
# Задача 2
from PIL import Image
def count_unique_colors(image) -> int:
    unique_colors = np.unique(
        image.reshape(-1, image.shape[2]), # каждая строка это 1 пиксель
        axis=0 # поиск уникальных строк по строкам
    ) # возвратит только уникальные пиксели
    """
    Например print(unique_colors[0:4]):
    [[  0   0   0   1]
     [  0   0 255   1]
     [  0 128 128   2]
     [  0 255 255   1]]
    """
    return unique_colors.shape[0]


image_path = './python-logo-only.png'
image = Image.open(image_path)

image_array = np.array(image, dtype=np.uint8)
print(image_array.shape)

num_unique_colors = count_unique_colors(image_array)
print("Количество уникальных цветов:", num_unique_colors)
image.show()


(326, 269, 4)
Количество уникальных цветов: 1406


Error: no DISPLAY environment variable specified


In [15]:
# Подсчёт времени выполнения
import time


def measure_time(func, *args):
    start = time.time()
    result = func(*args)
    elapsed_time = time.time() - start
    print(f'cur time = {elapsed_time}')
    return result

In [18]:
# Задача 3
def moving_average_cumsum(vector, window_size):
    """Через кумулятивную сумму"""
    if window_size <= 0 or window_size > len(vector):
        raise ValueError("Размер окна должен быть положительным и меньше или равным длине вектора.")
    
    cumsum = np.cumsum(vector)  # Кусочная сумма
    cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]  # Вычитание старых значений
    return cumsum[window_size - 1:] / window_size  # Возвращаем средние значения


def moving_average_convolution(vector, window_size):
    """Через свёртку"""
    if window_size <= 0 or window_size > len(vector):
        raise ValueError("Размер окна должен быть положительным и меньше или равным длине вектора.")
    
    return np.convolve(vector, np.ones(window_size) / window_size, mode='valid')
    # 'full': максимальное перекрытие;
    # 'same': результат того же размера, что и входной вектор;
    # 'valid': минимальное перекрытие, выводятся только "полные" свёртки.

# Пример использования
vector = np.array([1, 2, 3, 4, 5]) # np.arange(1, 5, 1)
#vector = np.arange(1, int(1e9), 2)
window_size = 3


ma = measure_time(moving_average_cumsum, vector, window_size)
print("Плавающее среднее cumsum:", ma)

ma = measure_time(moving_average_convolution, vector, window_size)
print("Плавающее среднее convolution:", ma)

cur time = 0.00014352798461914062
Плавающее среднее cumsum: [2. 3. 4.]
cur time = 0.0001430511474609375
Плавающее среднее convolution: [2. 3. 4.]


In [20]:
# Задача 4
import numpy as np

def valid_triangles(triplets) -> np.array:
    # triplets[:, 0] извлекает все значения из первого столбца массива triplets.
    # : (двоеточие) в индексации означает выбор всех строк.
    condition1 = triplets[:, 0] + triplets[:, 1] > triplets[:, 2]
    condition2 = triplets[:, 0] + triplets[:, 2] > triplets[:, 1]
    condition3 = triplets[:, 1] + triplets[:, 2] > triplets[:, 0]
    """
    condition1, condition2, condition3 — это логические массивы,
        которые содержат результат поэлементного сравнения.
    Каждый элемент этих массивов является булевым значением (True или False),
        в зависимости от того,
        выполнено условие для соответствующих элементов исходного массива или нет.
    """
    valid_mask = condition1 & condition2 & condition3

    return triplets[valid_mask]

# Пример
triplets = np.array([[3, 4, 5],
                     [1, 2, 3],
                     [5, 5, 5],
                     [1, 10, 12]])

valid_triplets = valid_triangles(triplets)
print("Тройки чисел, которые являются длинами сторон треугольника:\n", valid_triplets)


Тройки чисел, которые являются длинами сторон треугольника:
 [[3 4 5]
 [5 5 5]]


In [22]:
# Задача 5
def solve_linear_system(A, b):
    # Методом Гаусса
    n = A.shape[0]

    augmented_matrix = np.hstack([A, b.reshape(-1, 1)])
    
    # приведение к треугольному виду
    for i in range(n):
        # Нормализация ведущего (не нулевого) элемента
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]
        
        for j in range(i + 1, n):
            augmented_matrix[j] -= augmented_matrix[i] * augmented_matrix[j, i]

    # Обратная подстановка
    x = np.zeros(n)
    for i in range( n - 1, -1, -1):
        # augmented_matrix[i, -1] - значение в правой части (b)
        # np.dot(augmented_matrix[i, i + 1:n], x[i + 1:n]) - подстановка найденных корней
        x[i] = augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i + 1:n], x[i + 1:n])
        
    return x

def solve(A, b):
    A_inv = np.linalg.inv(A)
    result = A_inv @ b
    return result
"""
def solve_linear_system2(A, b):
    # Размерность матрицы
    n = A.shape[0]
    
    # Создаем расширенную матрицу
    augmented_matrix = np.hstack([A, b.reshape(-1, 1)]).astype(float)

    # Прямой ход методом Гаусса (векторизация вместо цикла)
    for i in range(n):
        # Нормализуем текущую строку (делим на ведущий элемент)
        augmented_matrix[i] = augmented_matrix[i] / augmented_matrix[i, i]

        # Вычитаем текущую строку из всех нижележащих строк
        mask = np.eye(n, dtype=bool)  # Создаем маску единичной матрицы
        mask[i, :] = False  # Исключаем текущую строку
        augmented_matrix[~mask[:, i]] -= np.outer(augmented_matrix[~mask[:, i], i], augmented_matrix[i])

    # Обратная подстановка (тоже векторизованно)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i + 1:n], x[i + 1:n])

    return x
"""


A = np.array([[3, 4, 2],
              [5, 2, 3],
              [4, 3, 2]])
b = np.array([17, 23, 19])


ma = measure_time(solve, A, b)
print(f"solve: {ma}")

ma = measure_time(solve_linear_system, A, b)
print(f"solve_linear_system: {ma}")
#solution = solve_linear_system(A, b)
#print("Решение системы линейных уравнений:", solution)


cur time = 0.008718013763427734
solve:, [3. 1. 2.]
cur time = 0.0007579326629638672
solve:, [ 6. -1. -1.]


In [23]:
# Задача 6


"""
Если A — матрица размером m×n, то сингулярное разложение представляется следующим образом:
    A = U*Σ* Vt

U — матрица размером m×m,
    содержащая левые сингулярные векторы
    (столбцы матрицы U образуют ортонормированный базис для пространства столбцов матрицы A).
Σ — диагональная матрица размером m×n,
    содержащая неотрицательные числа, называемые сингулярными числами.
    Эти числа являются квадратными корнями из собственных значений матрицы At * A.
Vt — транспонированная матрица размером n×n,
    содержащая правые сингулярные векторы
    (строки матрицы Vt образуют ортонормированный базис для пространства строк матрицы A).

Свойства:
    1) Сингулярные числа: Элементы диагонали матрицы Σ называются сингулярными числами матрицы A.
    Они отсортированы по убыванию и отражают "влияние" соответствующих сингулярных векторов на исходную матрицу.
    
    2) Ортонормированность: Столбцы матриц U и V являются ортонормированными векторами. 
    Это означает, что каждая пара столбцов из U или V ортогональна и имеет длину 1.
    
    3)Ранг матрицы: Ранг матрицы A равен количеству ненулевых сингулярных чисел.

Применения

1) Решение систем линейных уравнений:
    SVD можно использовать для нахождения наилучших приближений для переопределённых систем уравнений.

2) Сжатие изображений:
    Используя только первые k сингулярных чисел и соответствующие векторы, можно получить приближенную матрицу,
    что позволяет эффективно сжимать изображения.

3) Анализ главных компонент (PCA):
    SVD лежит в основе метода PCA, который используется для снижения размерности данных.
"""

A = np.matrix("1 0 1; 0 1 0; 1 0 1")
# singular value decomposition
U, S, Vt = np.linalg.svd(A)

print("U:\n", U)
print("S:\n", S)
print("Vt:\n", Vt)


U:
 [[-0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]
S:
 [2. 1. 0.]
Vt:
 [[-0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.         -0.70710678]]
